version: "3"

services:
  database:
    image: postgres:13.2
    container_name: database
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432

volumes:
  pgdata: